export const plans = [
  [
    {
      date: "2022-10-24",
      startTime: "10:00",
      endTime: "12:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "13:00",
      endTime: "14:00",
      location: "kumoh",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "14:30",
      endTime: "16:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "18:00",
      endTime: "21:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "21:00",
      endTime: "22:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-25",
      startTime: "09:00",
      endTime: "11:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "10:00",
      endTime: "12:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
    {
      date: "2022-10-24",
      startTime: "13:00",
      endTime: "14:00",
      location: "kumoh",
      details: "some details",
      isDup: true,
    },
    {
      date: "2022-10-24",
      startTime: "14:30",
      endTime: "16:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
    {
      date: "2022-10-24",
      startTime: "17:00",
      endTime: "20:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "21:00",
      endTime: "22:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "15:00",
      endTime: "16:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
    {
      date: "2022-10-24",
      startTime: "16:30",
      endTime: "18:00",
      location: "kit",
      details: "some details",
      isDup: false,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
  [
    {
      date: "2022-10-24",
      startTime: "12:00",
      endTime: "14:00",
      location: "kit",
      details: "some details",
      isDup: true,
    },
  ],
];
